### ISSUE TITLE
about the fork of angel https://github.com/dukefirehawk/angel

### ISSUE THREAD

**Issue by insinfo** [dukefirehawk/vtigercrm-6-0-postgresql#1]
Hello, my name is Isaque Neves, and I saw that you made a fork of the Angel Framework, I love Angel and I use it in many projects together with AngularDart, I am also thinking of making an Angel fork and renaming the project to be able to publish at https://pub.dev a new version with support for null security.
I would like to know if you want to join efforts with me in this work, I have already launched 4 new renamed packages, with support for null security,

**Comment by dukefirehawk** [comment]
Angel has been released as Angel3 with all the key packages now supporting NNBD. Noted it is not backward compatible as the minimum requirement is Dart 2.12.x and above. Take it for a spin if interested. Contributions and feedback are welcome.
